# Generated by Django 4.2.4 on 2023-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
